### ISSUE TITLE
Kernel does not shut down after loosing internet connection

### ISSUE THREAD

**Issue by yakutovicha** [oschuett/appmode#11]
Recently I've noticed a behaviour that in my opinion should be corrected: if my laptop looses the internet connection and then I close the corresponding tab in the web browser - the kernel keeps running in the background. 

To reproduce that behaviour one needs to do the following steps:
1)  run a notebook in the app-mode. 
2) disconnect the computer from the internet
3) close the tab
4) restore  the internet connection
... After that the kernel keeps running "forever"

Similar thing happens if one often puts his computer into a "sleep" mode: once the python kernel gets detached from jupyter app - the only way to kill it is to go to the "taks" and shut it down manually. 

I think there should be an automatic check that kills the kernel if it was not doing anything a certain amount of time. This will significantly reduce the use of computational resources.

**Comment by oschuett** [comment]
While I agree that zombie kernels are an issue, I don't think this should be address by Appmode.

In fact, the Jupyter developers have been discussing this for some time: https://github.com/ipython/ipython/issues/5539 and apparently they recently came up with a solution: https://github.com/jupyter/notebook/pull/2215 .

Note, that JupyterHub has it's own mechanism for clearing out idle sessions: https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle

And there is also an ongoing discussion about reconnecting to a notebook: https://github.com/jupyter/notebook/issues/1150 .
