### ISSUE TITLE
Typing a number causes app mode to crash out

### ISSUE THREAD

**Issue by JuanCab** [oschuett/appmode#12]
When running a Jupyter notebook (which happens to implement ipywidgets extensively, in case that matters), if I hit a number key on the keyboard while not over a text field, the appmode 'crashes out' in the sense that the source code suddenly appears and is rendered as markdown.  It seems to be the last cell that gets re-rendered as markdown initially, but other cells can change as well.

Has been reproducible on two different jupyter notebooks on two different macs.

**Comment by oschuett** [comment]
I can also reproduce it. Thanks for reporting.
What happens is that the Jupyter shortcut for inserting a markdown heading gets triggered. I'll see if I can disable the Jupyter shortcuts somehow when in appmode.

**Comment by oschuett** [comment]
So, in the latest release 0.4.0 the keyboard shortcuts are disabled when in appmode.
