### ISSUE TITLE
appmode does not work with ipywidgets.Tab

### ISSUE THREAD

**Issue by harmvanderheijden** [oschuett/appmode#14]
Thanks for creating a great Jupyter extension!

However, I do have a problem with ipywidgets.Tab structures. The problem can be reproduced with the following code:

```
import ipywidgets as ipw

class wid:
    def on_click(self,btn):
        self.txt1.value += "button clicked 1\n"
        self.txt2.value += "button clicked 2\n"
    def widget(self):
        self.txt1 = ipw.Textarea()
        self.txt2 = ipw.Textarea()
        tab = ipw.Tab([self.txt1, self.txt2])
        tab.set_title(0, 'txt 1')
        tab.set_title(1, 'txt 2')
        btn = ipw.Button(description='click me')
        btn.on_click(self.on_click)
        return ipw.VBox([tab, btn])    

wid().widget()
```

When this is run in notebook mode, clicking on the button causes text to appear in the textareas of the tabs. In appmode, nothing happens.

**Comment by oschuett** [comment]
I'm sorry, but I can not reproduce your problem. Which version of appmode and which browser are you using?

**Comment by harmvanderheijden** [comment]
... and neither can I... Very strange, this sample and my more complicated actual program really did not work yesterday and today both work perfectly fine in appmode. I really don't know why. Sorry to have wasted your time. BTW, I'm running version 0.3.0 (py36_0 build), installed with conda from the conda-forge channel

The one thing that I can imagine that may have something to do with this, is that after reporting this issue yesterday, I installed 'bqplot' (also via conda / conda-forge). Perhaps that shook up the Jupyter install a bit and forced a needed update. Or it could be user error (but I really did check my test case very carefully!).

Thanks for getting back to me on this issue.

**Comment by oschuett** [comment]
I'm glad it resolved itself :-)
