### ISSUE TITLE
sys.stderr now shown in appmode, only notebook mode

### ISSUE THREAD

**Issue by harmvanderheijden** [oschuett/appmode#15]
It's a minor issue, but I'm not seeing the stderr output in appmode. It works fine in notebook mode. I'm using version 0.3.0 and firefox 58. 

It seems that the HTML is generated, but the CSS is wrong (printing white letters on white background?) when in appmode. This happens both when just printing and when redirecting to a ipywidgets.Output

This will reproduce the problem:
```
import ipywidgets as ipw
import sys

class wid:
    def on_click(self,btn):
        print("normal print (stdout)")
        print("normal print (stderr)", file=sys.stderr)
        with self.txt1:
            print("redirected to txt1 (stdout)")
            print("redirected to txt1 (stderr)", file=sys.stderr)
    def widget(self):
        self.txt1 = ipw.Output()
        btn = ipw.Button(description='click me')
        btn.on_click(self.on_click)
        return ipw.VBox([btn, self.txt1])

wid().widget()
```

**Comment by oschuett** [comment]
Sorry for the late reply - I was traveling.
So, this behavior is actually intended because stderr is typically used for low-level messages that would confuse many users.

A possible workaround is be to redirect stderr to stdout:
```
sys.stderr = sys.stdout
```
