### ISSUE TITLE
deploying customized appmode via pip

### ISSUE THREAD

**Issue by ltalirz** [oschuett/appmode#16]
There are ways of [automatically enabling/installing jupyter notebook/server extensions](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#Automatically-enabling-a-server-extension-and-nbextension) using pip.

I wonder: Is it possible to deploy a customized version of appmode this way?

In order to swap e.g. the logo of the loader, one can use the `~/.jupyter/custom/custom.js` file with a content like this
```
$('#appmode-loader').replaceWith(`
<div id="appmode-loader">
<svg>
...
</svg>
</div>    
`);
```
but I don't think the `custom.js` file can be modified using the approach linked to above.
What would be the suggested approach to achieve this?

**Comment by oschuett** [comment]
Well, if you are contemplating to ship a modified version of appmode, then why don't you modify it directly?
You could e.g. just swap out gears.svg for something else, right?

**Comment by ltalirz** [comment]
Sure, it just means we'll need to keep the versions in sync.
If that's what you recommend then that's what we're going to do.

**Comment by oschuett** [comment]
How did you plan to maintain the second pip package? Is overwriting an existing file more problematic than adding a new one?

**Comment by oschuett** [comment]
Maybe instead of modifying appmode, you should create a second extension that merely customizes it. I guess you are also planning to tweak other parts of Jupyter, right?

**Comment by oschuett** [comment]
Ok, I'm gonna close this issue now. Let me know if there is anything you need from the appmode side.
