### ISSUE TITLE
Widget state not found, when page is reloaded

### ISSUE THREAD

**Issue by Stamenov** [oschuett/appmode#18]
I get the following message sometimes, but consistently, when I reload the app page:

A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.

**Comment by oschuett** [comment]
You could try to remove the cell widget output from the notebook by clicking `Cell` > `All Output` > `Clear` each time before your save the notebook. This way it should start out fresh when you hit reload.
