### ISSUE TITLE
Pass information from URL to AppMode Notebook

### ISSUE THREAD

**Issue by kmader** [oschuett/appmode#20]
This isn't really an issue more an idea that @betatim and I were discussing. Right now we have a very cheap fork of appmode  (https://github.com/chestrays/multiappmode) where we have added a handler for /muapps/useful_variable/notebook.ipynb which opens notebook in the root directory but sets `os.envion['APPMODE_USER'] = useful_variable` so whatever is running can take advantage of a piece of information in the URL. A concrete example is here: https://mybinder.org/v2/gh/chestrays/appmode/master?urlpath=%2Fmuapps%2Fmy_user_name%2Fexample_app.ipynb

Our idea would be to make this a bit more general and then upstream it into the main appmode. Rather than appending a path to the url, it might be more elegant to have a query string which gets parsed and put into environment variables (maybe with some prepended string to prevent overwriting something important).  Does this seem like it might be useful?

**Comment by oschuett** [comment]
This looks interesting. However, I don't understand why you can't use the ```jupyter_notebook_url``` variable?

**Comment by kmader** [comment]
I didn't know about the `jupyter_notebook_url` and that seems to keep the query string so it is perfect! Thanks
