### ISSUE TITLE
executing all cells leads to issues / configuration of run all

### ISSUE THREAD

**Issue by tharwan** [oschuett/appmode#22]
Hi,

I just discovered appmode and I am really glad it exists. With my current notebook I ran into the problem that appmode would not correctly display the UI. It would execute all cells after loading, step by step rendering all UI elements. But before it would finish the first elements would disappear again leaving only the last one.

I have no good explanation why that would be and I can also not share my notebook. In the notebook UI if I restart the kernel and run all cells it works just fine. 

I also discovered that the init cell plugin still works within appmode and if I trigger run all from within the first cell via an nationalization cell things are just fine. 

I would welcome it, if run all would indeed become an option to set in nbextension tab.

**Comment by oschuett** [comment]
Sorry for the late reply.

I'm afraid without some more info I'll have little chance of debugging this. In general appmode seems to work fine for many people. So, chances are you are doing something special? E.g. have you tried to disable the init cell plugin or nbextension altogether?

**Comment by oschuett** [comment]
I'm closing this issue for now. Feel free to re-open if there are any news.

**Comment by oschuett** [comment]
This was fixed by @parente via #28.
