### ISSUE TITLE
Control dimensions

### ISSUE THREAD

**Issue by DancingQuanta** [oschuett/appmode#23]
`appmode` is very nice piece of software!

I have a big Tab widget with height of 1000px. In appmode, only part of the widget is visible and is scrollable.
Would it be possible to make appmode expand to fit the widget or control the height of the appmode?

**Comment by oschuett** [comment]
Thanks, I'm glad you like it :-)

For the layout Appmode relies on the what Jupyter provides. The simplest way to make modification is probably monkey patching via [custom.js](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/JavaScript%20Notebook%20Extensions.html#custom.js). See also https://github.com/oschuett/appmode#customization.

**Comment by DancingQuanta** [comment]
Thank you for your swift response.

I will take a look at costom.js.

**Comment by oschuett** [comment]
Sure. Feel free to reopen the issue on demand.
