### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by terna** [oschuett/appmode#25]
Dear Ole,
wonderful appmode, I saw it in myBinder. 

Locally, in MacOS, clicking on the Appmode button I have the error:
<img width="834" alt="1" src="https://user-images.githubusercontent.com/1790769/50451592-4b22cf80-0935-11e9-8fd7-ae9e975cccf6.png">

My notebook infos are;
<img width="755" alt="2" src="https://user-images.githubusercontent.com/1790769/50451612-6ab9f800-0935-11e9-9b37-56c70519dad4.png">

I'm running your example and as a plain notebook, it works.

Many thanks in advance, Pietro

**Comment by oschuett** [comment]
This sound like the server extension is not enabled. Please try running the following command:
```
jupyter serverextension enable --py --sys-prefix appmode
```

**Comment by oschuett** [comment]
I'm closing this issue for now. Please reopen if the issue persists.

**Comment by cmarshall10450** [comment]
I have the same issue. 

I have enabled both the client and server side extensions with:
```bash
root@8dcb3205a874:~# jupyter nbextension     enable --py --sys-prefix appmode
Enabling notebook extension appmode/main...
      - Validating: OK
```
```bash
root@8dcb3205a874:~# jupyter serverextension enable --py --sys-prefix appmode
Enabling: appmode.server_extension
- Writing config: /opt/conda/etc/jupyter
    - Validating...
      appmode.server_extension  OK
```

I see the "appmode" button in notebooks but get "404: Not Found" when I run the app.

**Comment by oschuett** [comment]
That's strange. Did you restart the jupyter notebook server after installing appmode? Are there any clues in the the server log ?

**Comment by cmarshall10450** [comment]
Thanks for the quick reply.

I'll look at the logs for anything odd. I'm using JupyterHub and Jupyter Notebook server, both running as Docker containers. I installed appmode manually into the notebook container but I may need to make changes to both containers to get it to be configured when the notebook container is spawned.

**Comment by oschuett** [comment]
Yes, the notebook server definitely needs to be restarted in order to pickup the newly install server extension. So, the easiest solution is probably to move the Appmode installation into your Dockerfile.
