### ISSUE TITLE
jupyter nbextension validating failed

### ISSUE THREAD

**Issue by tina5870** [oschuett/appmode#26]
Just tried to use appmode for jupyter notebook by  following the readme.

Firstly I installed the appmode successfully for user:
    pip install --user appmode
Secondly I tried to enable the extension
    jupyter nbextension enable --py --user appmode
but it failed, showing like this
Enabling notebook extension appmode/main...
      - Validating: problems found:
        - require?  X appmode/main
When I tried jupyter serverextension enable --py --user appmode, the validating was successful.

Thanks for looking at the problem.

**Comment by oschuett** [comment]
There could be a number of reasons this. Most probably your python search path is wrong. In any case, this is not a particular Appmode issue. So, I'd like to refer you to the general Jupyter support forums.
