### ISSUE TITLE
Server Side Config And Limiting Access

### ISSUE THREAD

**Issue by gfleetwood** [oschuett/appmode#30]
Hey,

I just found this project. Great work! I had two questions:

* Is it possible to hide the Jupyter session from the user? That is, clicking the Jupyter logo in the top left would do nothing instead of leading back to the notebook file system. I did this from the UI by adding `onclick="return false;"` to the a tag. My attempt to make that the default behavior didn't work though. I tried that by adding  `document.querySelector('[title="a dashboard"]').setAttribute("onclick", "return false;");` to the custom.js file. My ultimate goal is to be able to present a simple quasi-web app to a user without them being able to access any of the Jupyter backend.

* Can you elaborate on how to implement server side configurations? Which files to edit and how to pass these into the notebook, for example? The README wasn't very clear.

**Comment by oschuett** [comment]
Your approach is certainly viable. Try:
```
$('#ipython_notebook > a').attr("onclick", "return false;");
```
However, note that your users will still be able to access the backend e.g. by simple typing the url manually.

**Comment by afeiszli** [comment]
Hi @oschuett, I am also very interested in this. Our team looked into Voila since it runs on a different port, so URL access can be restricted very easily. However it is very buggy; appmode runs much smoother. Have you had any success with restricting URL access to the rest of Jupyter?
