### ISSUE TITLE
Appmode error in Binder

### ISSUE THREAD

**Issue by joshwapiano** [oschuett/appmode#31]
Making this a new issue as I'm not sure of notifications for closed issue comments, apologies if you've seen my other message!
I'm  having trouble using appmode in Binder! I'm using a test document here as an example - the non-appmode link works fine:
https://mybinder.org/v2/gh/joshwapiano/amrtool/master?filepath=pandas_df_testing_01.ipynb

However changing filepath to urlpath and adding `%2Fapps%2F` as follows leads to a '404 : Not Found' error.
https://mybinder.org/v2/gh/joshwapiano/amrtool/master?urlpath=%2Fapps%2Fpandas_df_testing_01.ipynb

I tried adding a `binder/postBuild` file to my repository as is in yours but that completely broke the first link! (I'm also not sure whether that is necessary or not)

could this be because I'm using python 3.7 instead of 3.6?

**Comment by oschuett** [comment]
Try adding an `environment.yml` file to your repository with this content:
```
channels:
  - conda-forge
dependencies:
  - appmode
```

**Comment by joshwapiano** [comment]
Great - thanks for the response @oschuett . This has worked - my issue was that my .yml file was named `amr_lite_01.yml` rather than `environment.yml`.
