### ISSUE TITLE
Appmode not showint in extensions

### ISSUE THREAD

**Issue by ivanacorovic** [oschuett/appmode#33]
Hi,

I am new to Jupyter, so I am not sure what else to try. I've installed jupyter on a Mac (python 3.7.2). I've tried installing appmode with **conda** (all went well), but it does not show in the extensions, and I don't get the button. 

Then I tried with **pip**:
    `pip install appmode`
    `jupyter nbextension     enable --py --sys-prefix appmode`
    `jupyter serverextension enable --py --sys-prefix appmode`

Everything is fine, I get:

Enabling notebook extension appmode/main...
      - Validating: OK

- Writing config: /../jupyter
    - Validating...
      appmode.server_extension  OK

But still nothing. Any advice?

**Comment by oschuett** [comment]
Sorry for the late reply. Did you manage to solve the problem in the meantime? Your output looks unsuspicious. Maybe there are error messages when you start jupyter?

**Comment by ivanacorovic** [comment]
Hello Ole,

There were no errors, but I've updated my MacOS version and now it's
working!
Best regards,
Ivana

**Comment by oschuett** [comment]
Glad to hear :-)
