### ISSUE TITLE
Appmode.show_edit_button config in Jupyterhub

### ISSUE THREAD

**Issue by ashimmishra** [oschuett/appmode#36]
I have a jupyterhub instance and Appmode plugin is installed on it and it works fine. I want to change the config Appmode.show_edit_button but when I put that in jupyterhub_config.py it throws error  
NameError: name 'Appmode' is not defined
How can I fix it, is there any other way to put the config?

**Comment by oschuett** [comment]
This config option is a pretty new addition. Maybe you don't have the latest version (0.5.0) installed?
You can check it like this:
```
import appmode
print(appmode.__version__)
```

**Comment by ashimmishra** [comment]
Thanks for the quick answer. 
I do have the latest version 0.5.0, I  checked on the spawned docker container. I think I am not able to figure out where to put the config so that the spawned single user server has that in the options.
