### ISSUE TITLE
Put appmode on conda forge?

### ISSUE THREAD

**Issue by rsignell-usgs** [oschuett/appmode#4]
If we had appmode as a conda package, I think folks could just do `conda install appmod` and wouldn't have to worry about the commands here: https://github.com/oschuett/appmode/blob/master/binder/postBuild
because you can handle those in the conda package. 

@ocefpaf, please tell me if I'm off base here. 

I failed to get `appmod` going with `binder` on my notebook `appmode` branch here:
https://github.com/reproducible-notebooks/ERDDAP_timeseries_explorer/tree/appmode
but if I could have just added `- appmode` to my `environment.yml` it would have been easy (I think).

My `master` branch works fine on binder:
https://github.com/reproducible-notebooks/ERDDAP_timeseries_explorer/tree/master

**Comment by oschuett** [comment]
Yes, Conda packaging is top on my list. Give me another day or so.

I'm not sure your why your setup doesn't work. Judged by the build output it seems Repo2Docker simply ignores the `pip` entry in your `environment.yml`. Maybe you can use a `requirements.txt` until I have the conda package ready? See: https://github.com/oschuett/appmode/tree/master/binder

**Comment by rsignell-usgs** [comment]
@oschuett, could it be that binder bypasses my entire `environment.yml` when it sees the `./binder` subdirectory?

**Comment by rsignell-usgs** [comment]
Woo hoo, with my [requirements.txt](https://github.com/reproducible-notebooks/ERDDAP_timeseries_explorer/blob/appmode/binder/requirements.txt) and my beefed up [postBuild](https://github.com/reproducible-notebooks/ERDDAP_timeseries_explorer/blob/appmode/binder/postBuild), my `appmode` branch is working on binder:

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/reproducible-notebooks/ERDDAP_timeseries_explorer/appmode?urlpath=%2Fapps%2FERDDAP_timeseries_explorer.ipynb)

Thanks @oschuett and @jasongrout!    (cc: @ocefpaf)

**Comment by oschuett** [comment]
Done: https://anaconda.org/conda-forge/appmode

**Comment by rsignell-usgs** [comment]
Woohoo!!!   Works great on my simple test here:
https://github.com/rsignell-usgs/dc-wifi-social
