### ISSUE TITLE
Hide the Jupyter logo/button

### ISSUE THREAD

**Issue by marketneutral** [oschuett/appmode#41]
I am serving NBs via appmode with `--Appmode.show_edit_button=False`. However, users still see the "Jupyter" logo in the top left. If they click that, they are sent to the work tree out of the app. How would I hide this?

**Comment by oschuett** [comment]
The simplest solution would be via javascript. You could add the following cell to all your notebooks:
```
%%javascript
$('#header').hide();
```
Or you add it to your [custom.js](https://github.com/oschuett/appmode#client-side-customization).
