### ISSUE TITLE
Centering output without generating scrollbars

### ISSUE THREAD

**Issue by manuelknott** [oschuett/appmode#42]
I try to center the output of my cells (ipython widgets) with the following command:

```
display(HTML("""
<style>
.output {
    display: flex;
    align-items: center;
    text-align: center;
    overflow: hidden;
}
</style>
"""))
```

The output gets centered but now a unwanted horizontal scrollbar appears in appmode (does not appear in notebook mode).

Any idea what might be the reason for this? Does appmode use the same CSS settings as notebook mode?

**Comment by oschuett** [comment]
Yes, Appmode uses the same CSS and only hides some elements by loading [appmode_bottom.css](https://github.com/oschuett/appmode/blob/master/appmode/appmode_bottom.css).
