### ISSUE TITLE
tmp copies deletion failed

### ISSUE THREAD

**Issue by sfluo** [oschuett/appmode#45]
When a notebook in appmode gets closed, the temporary copy will be deleted via DELTE request, however, I constantly saw errors on this regard

[E 21:58:52.525 NotebookApp] Uncaught exception DELETE /apps/.Welcome-5.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='DELETE', uri='/apps/.Welcome-5.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "~/.venv/xapp/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "~/.venv/xapp/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "~/.venv/xapp/lib/python3.7/site-packages/appmode/server_extension.py", line 97, in delete
        sm.delete_session(session_id=s['id'])
    TypeError: '_asyncio.Future' object is not subscriptable

500 DELETE /apps/.Welcome-5.ipynb (::1) 5.01ms referer=http://localhost:8888/apps/Welcome.ipynb

**Comment by oschuett** [comment]
Which version are you using?
This sounds like something that should have been fixed with the [0.7  release](https://github.com/oschuett/appmode/releases/tag/v0.7.0).
