### ISSUE TITLE
How to initiate appmode from terminal?

### ISSUE THREAD

**Issue by vmlenart** [oschuett/appmode#46]
Hi, I am looking for the same feature of [voilà]...
$ voila some_file.ipynb
How can I run the same feature with appmode?

**Comment by oschuett** [comment]
Sorry for the late reply. You can open a webbrowser form the terminal like this:
```
firefox https://mybinder.org/v2/gh/oschuett/appmode/master?urlpath=%2Fapps%2Fexample_app.ipynb
```
