### ISSUE TITLE
How to hide the tree of an ipywidgets application with appmode?

### ISSUE THREAD

**Issue by idespindola** [oschuett/appmode#47]
I created a simple application for my work using ipywidgets with Appmode. I need to hide the tree of notebook in AppMode On (I practically want to hide the logo and the link below.).

![sistema-mostrar](https://user-images.githubusercontent.com/13322651/74393890-151b0600-4dea-11ea-8e15-22ffdea086b9.png)

**Comment by vhorvath** [comment]
Hi @idespindola,

There are some pointers in the [StackOverflow post](https://stackoverflow.com/questions/44298864/how-can-i-eliminate-the-gray-border-around-jupyter-ipython-notebooks-in-my-brows).

For a full hide you would do something like:
```
from IPython.core.display import HTML
display(HTML(
    '''<style>
        #header { display: none !important; }
        #notebook { padding-top: 0px !important; }
        .container { width:100% !important; padding-top: 0px !important}
        .end_space { min-height: 0px !important; }
    </style>'''
))
```

**Comment by oschuett** [comment]
Have a look at the config options on the [server-](https://github.com/oschuett/appmode#server-side-configuration) and [client-side](https://github.com/oschuett/appmode#client-side-customization).
