### ISSUE TITLE
How can I pause the execution of the rest of the notebook until a form is completed?

### ISSUE THREAD

**Issue by baharev** [oschuett/appmode#49]
The use case is the following. 

First, the user has to fill out a "form" on the top the notebook. I am using ipywidgets for collecting the input from the user. The user can signal that the input is complete by clicking a button. 

Then, the rest of the notebook should be executed. Without all the input data, the rest of the notebook cannot be executed.

How can I pause the execution of the rest of the notebook until the form is completed?

If the rest was plain Python code, I could invoke it in the event handler, and be done with it. I don't know how to execute "the rest of the notebook" in an event handler.

My apologizes if I overlooked something trivial. I greatly appreciate your help.

**Comment by baharev** [comment]
Here is a horrible workaround:

```python
# In [1]:
from IPython.display import Javascript as JS, display
import ipywidgets as ipw

def run_the_rest():
    display(JS('Jupyter.notebook.execute_cell_range(2, Jupyter.notebook.ncells());'))

def on_click(btn):
    print('Clicked!')
    run_the_rest()

btn = ipw.Button(description='Run', layout=ipw.Layout(width="45px"))
btn.on_click(on_click)
btn

# In [2]:
raise Exception('Horrible hack to stop the kernel')

# In [3]:
print('Done!')
```

If I had a way to customize the extension, and instead of [running all cells](https://github.com/oschuett/appmode/blob/d562abf35513e3440fc70b83f178ed151f445bcc/appmode/static/main.js#L166), I could specify how far it should run, there would be no problem. Alternatively, if there was a more intelligent way of stopping the kernel instead of raising an exception, that would be another acceptable workaround.

Any help is greatly appreciated.

**Comment by oschuett** [comment]
The simplest solution would be if you placed all the code for deferred execution into functions. When the notebook cells execute they only define the function, which you can then call later.

**Comment by baharev** [comment]
As I wrote in the first comment: *"If the rest was plain Python code, I could invoke it in the event handler, and be done with it."* 

So yes, I sort of agree, unfortunately, the rest of the notebook really is a notebook and not plain Python code. Those deferred executions will create matplotlib plots and/or new widgets. It's not clear to me how to add them cleanly to the notebook from inside a widget event handler...

Another issue is that it interferes with the use case. The notebook is developed as a notebook, and when I consider it "done", I would like to turn it into a web app with your extension with the least amount of pain. If I have to restructure the entire notebook so that I can turn it into a web app, it makes your extension less useful for this use case.

Just for the record: The use case is that I first collect the input data through widgets, then execute the rest of the notebook. It seems a pretty common and reasonable use case to me.

**Comment by baharev** [comment]
One workaround would be to give the control back to the user. So instead of:

```javascript
Jupyter.notebook.execute_all_cells();
```

your extension could check if the caller wants to do some custom execution, and if so, give the control back. I could pass in my own function in `custom.js` through the window object. Something like:

```javascript
const custom_exec = window.APPMODE_CUSTOM_EXECUTE;
if (custom_exec) {
   custom_exec();
else
    Jupyter.notebook.execute_all_cells();
```

It's not nice to mess with the `window` object but it is easy to implement.

**Comment by oschuett** [comment]
> It's not nice to mess with the window object but it is easy to implement.

I really don't think this is necessary. It should be possible to achive what you want with pure Python.
You can append output to a notebook by calling [display](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display).
If you want to have more controll over where output appears, have a look at the [OutputWidget](https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html).

**Comment by baharev** [comment]
Thanks for the suggestion and for the info. We will need more time to discuss whether the `OutputWidget` is appropriate for our use cases.

I looked at the documentation and it seems to me it is not good for the use cases I care about.

However, we will have to go through all the other use cases, and figure out how much extra work it is to restructure the notebooks and use the `OutputWidget`.

I will get back to you on this topic in 2 weeks time.

Thanks again for the help and for the suggestion.

**Comment by baharev** [comment]
I think we are in this classic situation:
![3-or-4](https://user-images.githubusercontent.com/2605584/80030899-2e76b780-84e9-11ea-86f2-de95a6db3dbd.jpg)
I totally get your point, and why you are saying 4. I still think that the development work flow I described in [this comment](https://github.com/oschuett/appmode/issues/49#issuecomment-611566083) (I am saying 3) is a valid and reasonable work flow / use case, and it should be possible to customize what `appmode` executes.

As for the other use cases we have, `appmode`'s default behaviour is OK.

As far as I am concerned, you can close this issue. Thanks for your suggestion, help, and patience!

**Comment by oschuett** [comment]
Your welcome. I hope you find a workable solution.
