### ISSUE TITLE
404 Page not found error - AWS Sagemaker

### ISSUE THREAD

**Issue by rhythem** [oschuett/appmode#50]
Hi,

I am trying to make Appmode work for AWS Sagemaker's Notebook instance but it throws the 404 Page not found error. Any help would be greatly appreciated. (Let me know what information is needed to debug this)

**Comment by oschuett** [comment]
I'm not familiar with AWS Sagemaker. Are you sure that the server extension has been installed too?
What's the URL of the 404 page?

**Comment by rhythem** [comment]
Thankyou for your response. Below are the details on how i have installed the notebook extention and enabled them
```

#!/bin/bash
set -e
sudo -u ec2-user -i <<'EOF'
source /home/ec2-user/anaconda3/bin/activate JupyterSystemEnv
pip install appmode
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
source /home/ec2-user/anaconda3/bin/deactivate
EOF

```

Below is the URL of the 404 Page. (I have masked some part of the URL since it is a client page)

> https://aws-a0031-use1-xxxxxxxxxx-sag01.notebook.us-east-1.sagemaker.aws/apps/Processes/Oncology/Untitled.ipynb?appmode_scroll=0

Below is the screenshot of the page

![image](https://user-images.githubusercontent.com/2235336/81059286-cdd67a00-8eed-11ea-9b14-2e7a4d0d9cfd.png)

**Comment by oschuett** [comment]
I see you are using Conda. Have you tried installing it from Conda-Forge:
```
conda install --channel conda-forge appmode
```
