### ISSUE TITLE
Temp notebook copies and kernels never removed

### ISSUE THREAD

**Issue by sethgilchrist** [oschuett/appmode#51]
When I launch an apps link, the my notebook is correctly copied and a new kernel started; however, they are never deleted/shutdown, which leaves me with a large number of junk files and running kernels.  Is there a config I should modify to ensure this happens?

Win 10 Pro 64bit
python 3.7.5
appmode 0.7.0
jupyter-core 4.6.1
jupyter-client 5.3.4

**Comment by oschuett** [comment]
The cleanup is triggered via [window.onbeforeunload](https://github.com/oschuett/appmode/blob/master/appmode/static/main.js#L126). Unfortunately, this is not very reliable because browsers are hesitant to execute javascript after the user left the page.

Do you see the `DELETE` requests in the server logs?

**Comment by sethgilchrist** [comment]
I don't see any delete commands. Here are the lines for opening and closing of an appmode notebook in Chrome Version 81.0.4044.129:

```
[I 10:07:08.331 NotebookApp] Appmode get: AppUi.ipynb
[I 10:07:08.332 NotebookApp] Appmode creating tmp copy: /.AppUi-5.ipynb
[I 10:07:09.465 NotebookApp] Kernel started: 82b4101e-5bf4-4a47-9a3b-7239d338d035
<<<< Note: Appmode Notebook closed here >>>>
[I 10:07:22.257 NotebookApp] Starting buffering for 82b4101e-5bf4-4a47-9a3b-7239d338d035:f24cc1af975b43e98d1baee777de24ff
```

**Comment by oschuett** [comment]
It indeed seems like the `DELETE` requests are not send. Are there any messages in the browser's web console? As said before, `window.onbeforeunload` is unfortunately know to be unreliable.

**Comment by yakutovicha** [comment]
We have also noticed this problem. One little detail: the apps do get closed in Firefox, but not in Chrome.

**Comment by oschuett** [comment]
Apparently, there was a recent change in chrome, which [disallow sync XHR in page dismissal](https://www.chromestatus.com/feature/4664843055398912).

Could you once try if setting `async: true` in [main.js:25](https://github.com/oschuett/appmode/blob/master/appmode/static/main.js#L25) helps?

**Comment by yakutovicha** [comment]
> Could you once try if setting `async: true` in [main.js:25](https://github.com/oschuett/appmode/blob/master/appmode/static/main.js#L25) helps?

Yes, I tried: the problem gets resolved for Chrome, but shows up for Firefox.

**Comment by oschuett** [comment]
Ok, it seems the proper way these days is [sendBeacon()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon). That [API](https://golb.hplar.ch/2018/09/beacon-api.html) only sends `POST` requests. So, the server side has to be adopted as well. 

@yakutovicha, do you want to give it a try? I'm not sure I'll find time for it this week.

**Comment by ltalirz** [comment]
Just a shot in the dark but what about using the more generic [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead to be able to keep using a `DELETE` request and not modify the backend? 
Browser compatibility seems to be the same.

See [here](https://github.com/w3c/beacon/pull/27#issuecomment-241549321) for an example of replacing a `sendBeacon()` with a `fetch` call.

@oschuett If you could have a guess as to how the `fetch` call should look like, we could test it out.

**Comment by oschuett** [comment]
I think, `sendBeacon()` is the safer choice because it's explicitly designed to work with `onbeforeunload`. Overall the changes - also on the server side - should be rather straight forward.

**Comment by yakutovicha** [comment]
> I think, `sendBeacon()` is the safer choice because it's explicitly designed to work with `onbeforeunload`. Overall the changes - also on the server side - should be rather straight forward.

Hi @oschuett. I am personally not very experienced in javascript, so I would really leave the fix to somebody who knows better what they are doing. However, I was wondering, if it would make sense to do a temporary fix of a sort: `if chrome then async: true, else async: false`? 

I can do that rather quickly. And then we could wait for a more future-proof fix.

Let me know.

**Comment by oschuett** [comment]
I took a [first stab](https://github.com/oschuett/appmode/commit/8665aa6474164023a9f59a3744ee5ffe5c3a8b4a) at it. Let me know if it works for you.

**Comment by yakutovicha** [comment]
thanks, @oschuett, it seems to work! I checked on Firefox, Chrome, Safari

**Comment by EngineerReversed** [comment]
> thanks, @oschuett, it seems to work! I checked on Firefox, Chrome, Safari

I tried the above changes but it did not work for me. On looking into jupyter logs, I found the following : 
```
405 POST /apps/notebooks/notebooks/.example.ipynb (172.17.0.5) 2.05ms referer=<link>
```
Is it due to the fact that it is not able to delete the file as it doesn't have permissions?

Chrome version : `Version 80.0.3987.163 (Official Build) (64-bit)`

PS : I am using docker with `appmode` installation in root mode.

**Comment by oschuett** [comment]
@EngineerReversed, it's hard to say without more information.
Maybe you can run with `jupyter-notebook --log-level=DEBUG` ?

**Comment by EngineerReversed** [comment]
> @EngineerReversed, it's hard to say without more information.
> Maybe you can run with `jupyter-notebook --log-level=DEBUG` ?

I tried the same on my local mac and it was able to delete temporary copies of notebook and shut down kernels as well.
```
[I 17:47:26.010 NotebookApp] Appmode get: Untitled.ipynb
[I 17:47:26.012 NotebookApp] Appmode creating tmp copy: /.Untitled-0.ipynb
[I 17:47:27.917 NotebookApp] Kernel started: 27c5fadb-eaac-4085-9ffe-eefdbadd039d
[I 17:47:30.229 NotebookApp] Adapting to protocol v5.1 for kernel 27c5fadb-eaac-4085-9ffe-eefdbadd039d
[I 17:47:46.272 NotebookApp] Starting buffering for 27c5fadb-eaac-4085-9ffe-eefdbadd039d:688c71af33ae400489a16697320c2ff4
[I 17:47:46.305 NotebookApp] Appmode deleting: .Untitled-0.ipynb
```

I guess it has something to do with permissions on server. I will look into it and let you know.

**Comment by EngineerReversed** [comment]
On further series of experiments, I was able to localize the bug. I had not uninstalled the previous version of `appmode` and install newer version after cloning from github using `python setup.py install`.
It also did not allow *nbextention* to be enabled as well.
```
Enabling notebook extension appmode/main...
      - Validating: problems found:
        - require?  X appmode/main
```

After installing it via `pip install .` and enabling `appmode` in extensions, it deleted the temporary copies successfully.
```
[I 19:37:00.594 NotebookApp] Appmode get: notebooks/notebooks/Taxonomy_EDA_Demo.ipynb
[I 19:37:00.594 NotebookApp] Appmode creating tmp copy: notebooks/notebooks/.Taxonomy_EDA_Demo-0.ipynb
[I 19:37:03.353 NotebookApp] Kernel started: 67a90f1b-e48f-48ce-9ecb-8db328c06228
[I 19:37:04.076 NotebookApp] Adapting to protocol v5.1 for kernel 67a90f1b-e48f-48ce-9ecb-8db328c06228
[I 19:37:34.060 NotebookApp] Appmode deleting: notebooks/notebooks/.Taxonomy_EDA_Demo-0.ipynb
[I 19:37:34.363 NotebookApp] Kernel shutdown: 67a90f1b-e48f-48ce-9ecb-8db328c06228
[W 19:37:34.364 NotebookApp] Skipping trash for /home/jupyter/notebooks/notebooks/.Taxonomy_EDA_Demo-0.ipynb, on different device to home directory
[W 19:37:34.368 NotebookApp] zmq message arrived on closed channel
```

> I took a first stab at it. Let me know if it works for you.

You can release a new version with this patch.

**Comment by oschuett** [comment]
Alright, I've made a [new release](https://github.com/oschuett/appmode/releases/tag/v0.8.0). Thanks for your help!
