### ISSUE TITLE
404 Not Found Error after clicking "Appmode" button

### ISSUE THREAD

**Issue by nehana** [oschuett/appmode#54]
Clicking appmode takes me to this page
![image](https://user-images.githubusercontent.com/20363571/85085049-733a6a00-b18b-11ea-905e-4eba91509c55.png)

**Comment by oschuett** [comment]
Most probably the server extension is not properly installed.
You can check this by running `jupyter serverextension list` on the command line.

**Comment by nehana** [comment]
![image](https://user-images.githubusercontent.com/20363571/85217265-9c9df600-b343-11ea-8d66-57ac428dfd33.png)
This is what I got when I ran that on the command line.  What else can I do to troubleshoot?  Thank you for your help!

**Comment by oschuett** [comment]
Seems like the server extension is properly installed.

> What else can I do to troubleshoot? 

You could run the sever with debugging output:
```
jupyter-notebook --log-level=DEBUG
```

Also, what's the exact URL that give you the 404 error?

**Comment by yvanarnaud** [comment]
Hi,
I had  the same problem. It turned out I had to install ipywidgets.

**Comment by oschuett** [comment]
Without ipywidgets I get the following message:

![ipywidgets_missing](https://user-images.githubusercontent.com/241771/85893510-4d4c3f80-b7f3-11ea-8c35-1ae564a42279.png)

So, I don't think missing ipywidgets can be responsible for 404 errors.

**Comment by nehana** [comment]
I haven't changed anything in my system, but I'm unable to reproduce the error.  App mode is now working perfectly!  Thank you for your help.

**Comment by oschuett** [comment]
Glad to here :-)

**Comment by chaffra** [comment]
Hi, I know this is closed but I am getting the same error as above. How did you solve it?
