### ISSUE TITLE
404 Error When Automatically Triggering Appmode

### ISSUE THREAD

**Issue by edsto1** [oschuett/appmode#55]
My apologies if this has already been answered, but I have dug through the closed issues of users having this same problem but none of the solutions have worked for me thus far.

I am receiving a 404 Page Not Found error when amending my URL to trigger appmode automatically in Binder. Using my notebook here works fine, and appmode can be triggered within the notebook and work as it should:

https://mybinder.org/v2/gh/edsto1/Covid19_Analysis_and_Insights/master?filepath=%2FDeep_Learning_ANN_Predictive_Model.ipynb

when add the "%2Fapps%2F to the path in the URL, i get a 404 error:

https://mybinder.org/v2/gh/edsto1/Covid19_Analysis_and_Insights/master?filepath=%2Fapps%2FDeep_Learning_ANN_Predictive_Model.ipynb

I've tried to update conda, and running `jupyter serverextension enable --py --sys-prefix appmode` before hand. Any ideas?

**Comment by oschuett** [comment]
You have to use `urlpath` instead of `filepath`:
https://mybinder.org/v2/gh/edsto1/Covid19_Analysis_and_Insights/master?urlpath=%2Fapps%2FDeep_Learning_ANN_Predictive_Model.ipynb

Nice app btw :-)

**Comment by edsto1** [comment]
*Face palm *
Of course, not sure how I overlooked that, Thanks!

**Comment by oschuett** [comment]
No problem. Your welcome.
