### ISSUE TITLE
How could I keep the same kernel when I lanch the appmode 

### ISSUE THREAD

**Issue by huyuhuster** [oschuett/appmode#57]
Every time I launch the app mode, I see the kernel will be shut down and started. Then the kernel changed. But I want to keep the same kernel. Do you have any method to keep the same kernel or avoid to restart?

**Comment by oschuett** [comment]
Unfortunately, reusing the kernel is not possible, because the entire html page needs to be reloaded when switching from normal to appmode. Sorry!
