### ISSUE TITLE
Is it possible to autostart in appmode?

### ISSUE THREAD

**Issue by njesp** [oschuett/appmode#58]
Stackoverflow does not seem to be able to help, https://stackoverflow.com/questions/64895308/how-do-i-autostart-jupyter-notebook-in-appmode

So, I decided to five it a try here.

**Comment by oschuett** [comment]
You can directly link to the appmode version of a notebook, e.g. like this:

https://mybinder.org/v2/gh/oschuett/appmode/master?urlpath=%2Fapps%2Fexample_app.ipynb
