### ISSUE TITLE
Unable to view the appmode button on google colab

### ISSUE THREAD

**Issue by pragnyas** [oschuett/appmode#59]
I have installed the appmode extension on google colab. However, I'm unable to view the appmode button. Is there something I'm missing?
![image](https://user-images.githubusercontent.com/68215098/107920430-fae2ad80-6f92-11eb-97a7-f812c42eed8f.png)

![image](https://user-images.githubusercontent.com/68215098/107921579-b9eb9880-6f94-11eb-90fd-bb08a8184d5b.png)

**Comment by oschuett** [comment]
AFAIK, Google Colab is a fork of the original Jupyter frontend. Since Appmode hooks into the Jupyter HTML templates, I'm not surprised that it doesn't work with Colab. Sorry!

**Comment by pragnyas** [comment]
Alright! Thank you for your time.
