### ISSUE TITLE
Enable appmode at startup by default

### ISSUE THREAD

**Issue by ltalirz** [oschuett/appmode#6]
How do I configure jupyter such that appmode is enable at startup?
I've installed the nb and server extensions (and appmode works), but by default a jupyter notebook will start in "regular" mode.
I'm sure there is an easy way to do it, but somehow it is escaping me so far...

**Comment by oschuett** [comment]
You can configure Jupyter's default URL via `--NotebookApp.default_url`. Like for example done [here](https://github.com/materialscloud-org/mc-docker-stack/blob/master/start-singleuser.sh#L134).

**Comment by ltalirz** [comment]
Thanks a lot!
