### ISSUE TITLE
Disable buttons and allow only Appmode

### ISSUE THREAD

**Issue by yb23** [oschuett/appmode#61]
Hello,

I am currently trying to install the appmode extension on a remote server. It works well in the base configuration.
But I would like to let access to some notebooks only in appmode and without the buttons ("Edit App", "Logout"). Thus I created a jupyter configuration file. (It is located in /root/.jupyter, whereas appmode is in /opt/appmode.) 
And when I add appmode.trusted_path='/opt/appmode/trusted/' and appmode.show_edit_button=False, it doesn't change anything in the notebooks.
Could you please help me to solve this problem ? I don't understand what I'm doing wrong ?
Thanks for your help.

**Comment by oschuett** [comment]
Sorry, somehow this question slipped through the cracks.
