### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by chaffra** [oschuett/appmode#63]
Just installed appmode on WSL. The button shows up in the classic jupyter notebook interface but I have a permission error:
```Cannot create file or directory '/home/me/Projects_/Model/.Model-0.ipynb'```
I own everything on that path.

**Comment by oschuett** [comment]
This is most certainly a problem with WSL rather than Appmode. I'd suggest to ask e.g. here: https://learn.microsoft.com/en-us/answers/questions/index.html
