### ISSUE TITLE
Setting a default kernel for appmode?

### ISSUE THREAD

**Issue by zarif98** [oschuett/appmode#67]
I have a virtual environment that I'd like to set as default every time I run my code. Right now it's running the application with my default environment and I have to manually click on my virtual environment within the kernel to use the right one. I'd like to have it where it picks the right one automatically when running the notebook.

**Comment by oschuett** [comment]
The Jupyter server offers a lot of [configuration options](https://jupyter-notebook.readthedocs.io/en/stable/config.html) regarding kernels.
In your case `MultiKernelManager.default_kernel_name` might do the trick.
