### ISSUE TITLE
Is it possible to make code non-writable?

### ISSUE THREAD

**Issue by einarbmag** [oschuett/appmode#7]
Hi, 
I'm looking for a way to expose notebook output to non-developers, but would ideally like the view to be locked such that the underlying code can't be altered. I've looked into the retired jupyter-dashboards project, but I'm having trouble getting the Cloudfoundry server setup to work. Is it possible to use appmode in this way, i.e. so that the code can't be changed?

**Comment by oschuett** [comment]
Hi,
due to Jupyter's architecture the entire notebook is always first downloaded into the browser and then the code cells are send back to the server one at a time. Hence, a users with enough expertise will always be able to intercept the code and alter it.

However, a way to keep non-developers from stumbling into the code could be to simply hide the "Edit App" button. Would that work for your use case?

**Comment by einarbmag** [comment]
Yes - that should do the trick! As you say, I would have to do something fancier if I wanted to lock down the code completely, but I mainly want to show some widgets to non-developers in my team. Is there an easy way to hide the button when accessing "baseurl/apps/foo.ipynb"  ?

**Comment by oschuett** [comment]
> Is there an easy way to hide the button when accessing "baseurl/apps/foo.ipynb" ?

Not yet.

I've been thinking what would be the best way to implement this. How about an additional url parameter, eg.: `baseurl/apps/foo.ipynb?appmode_edit=0` ? This could then set a cookie to keep the button hidden also on subsequent notebooks. The button could be re-enable via `?appmode_edit=1` or simply by removing the cookie.

**Comment by einarbmag** [comment]
Yes, that sounds reasonable. 

Would it be possible to also have a way to use a config file or command line flags to completely disable the button? Then one wouldn't need that extra URL parameter.

**Comment by oschuett** [comment]
Yes, I found a very simple solution. Just add the following line to your [custom.js](http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/JavaScript%20Notebook%20Extensions.html#custom.js) file:
```
$('#appmode-leave').hide();
```
Beware that users can still change the URL manually though.

**Comment by oschuett** [comment]
I added a readme section about [customization](https://github.com/oschuett/appmode#customization). Hence, I'll now close this issue.
