### ISSUE TITLE
Launch directly to Appmode view in MyBinder sessions doesn't seem to be working

### ISSUE THREAD

**Issue by fomightez** [oschuett/appmode#75]
Right now when I launch the appmode demo from the link from the 'launch binder' badge on the main READEME page (https://mybinder.org/v2/gh/oschuett/appmode/master?urlpath=%2Fapps%2Fexample_app.ipynb), though it is supposed to open in the appmode view, it just hangs on a blank page.

I tried playing around the URL and couldn't find the magic combination to make launching into Appmode directly work for now. However, while maybe I just didn't find the magic combination yet? And of course, it would be nice if the established way continued to work.  
I believe it is related to [this issue from back around October](https://github.com/jupyterhub/nbgitpuller/issues/329#issuecomment-1757840125) when a lot of the custom URL tricks (RStudio, nbgitpuller, and nbparam) stopped working correctly.  
The reason I saw that is because if I got the token then into the session by opening Jupyter normal first or added it to the URL then it worked. And that seems to be the case here. **Direct launch into that Appmode view doesn't work, but once you open Jupyter first then you can use the same URL and it works to get to the Appmode view.** So it seems to be similar to what I saw before.    
Note, that in that case luckily @yuvipanda from the MyBinder team got involved and fixed most of these. I believe Appmode maybe wasn't fixed?   
However, I totally could be mis-diagnosing this issue.

### Temporary work around to get to Appmode view on MyBinder:

Launch with https://mybinder.org/v2/gh/oschuett/appmode/master?urlpath=%2Fnotebooks%2Fexample_app.ipynb and then click on the 'Appmode' button.

What that URL is doing is launching the session in the Jupyter Notebook interface and then letting the user click the 'Appmode' button.

**Obviously this workaround is less than idea because it would be nice to to have the option to go directly to Appmode view.** However, it at least gives users a chance to use the Appmode in MyBinder-served sessions while this is worked out. At least [one person](https://stackoverflow.com/q/77889441/8508004) has been trying to use it and this is how I stumbled upon this apparent issue.

**Comment by oschuett** [comment]
Thanks for your report @fomightez. I can reproduce the issue. FWICT, none of Mybinder's APIs have changed. So, I'm not sure what I can do about it?

**Comment by fomightez** [comment]
Yes, I thought you might be limited in what you could do. However, before I assumed it was on the MyBinder site entirely, I wanted to be sure I wasn't mistaken. I'll try to remember to point this out somewhere the MyBinder team can see it.

**Comment by oschuett** [comment]
It seems MyBinder has fixed this issue.
