### ISSUE TITLE
Add a kernel status icon like the one from notebook mode

### ISSUE THREAD

**Issue by ocefpaf** [oschuett/appmode#9]
Some long running process on appmode gives the impression that things are not working while in fact it is just slow. It would be nice if appmode could show the kernel status so we know things are "running."

ping @rsignell-usgs

PS: appmode is awesome! Thanks for writing it!!

**Comment by rsignell-usgs** [comment]
Here's an example appmode app that would really benefit from such a "running" indicator:
https://mybinder.org/v2/gh/reproducible-notebooks/Tides_TriMesh_Datashader/master?urlpath=%2Fapps%2Ftide_trimesh_widgets.ipynb

**Comment by oschuett** [comment]
Thanks for the support :-)

How about using the ipython progress bar? It would allow you to also give the user some expectation about the required time.

Simply add this as your first cell at the top of your notebook:
```
import ipywidgets as ipyw
import time
import _thread
nseconds = 30
progress = ipyw.IntProgress(value=0, max=nseconds)
def update_process():
    for i in range(nseconds):
        progress.value = i
        time.sleep(1)
_thread.start_new_thread(update_process, ())
display(progress)
```

And when everything is ready you call ```progress.close()```.

PS: You can disable the scrolling of output cells via `Menu`->`Cell`->`Current Output`->`Toggle Scrolling`.

**Comment by oschuett** [comment]
Btw, I just noticed that the page's favicon conveys the kernel status.

**Comment by ocefpaf** [comment]
The favicon is far from the users eyes and maybe my notebook bias wants to see the usuall

![screenshot from 2018-03-29 12-31-14](https://user-images.githubusercontent.com/950575/38098010-420d9678-334d-11e8-9dee-e12896011e2a.png)

The progress bar is a nice workaround and, if you don't think `appmode` should have its own kernel status, feel free to close this.

**Comment by oschuett** [comment]
You've got a point. Hence, I added a simply busy indicator https://github.com/oschuett/appmode/commit/6e33cd33a5a96b8d04ae2e45fbe760a02069ee2c .

**Comment by ocefpaf** [comment]
Awesome! Thanks!!

**Comment by rsignell-usgs** [comment]
@oschuett, I must be missing something obvious, but although I installed the latest version, I don't see this busy indicator when running.  Where is it supposed  to appear?  Or do I need to activate it somehow?

**Comment by oschuett** [comment]
The busy indicator is simply a smaller version of the rotating gear wheels:

![busy_example](https://user-images.githubusercontent.com/241771/38150853-371c2a44-3461-11e8-8caf-087100859727.png)
It's currently only in git master. Now that I have figured out the conda forge stuff, I'll prepare a new release.
